### ISSUE TITLE
找不到类org.tensorflow.lite.Interpreter

### ISSUE THREAD

**Issue by woodboard** [benjaminwan/ChineseTtsTflite#13]
aar 和模型导入之后报错找不到类org.tensorflow.lite.Interpreter ，目录结构如下
![%KCT{0L5)%K{% AS~@KQSO5](https://github.com/user-attachments/assets/1d409b1e-12fb-47d0-b92a-d81fe8850abe)

**Comment by woodboard** [comment]
大神是不是改了aar 忘了更新android代码？ 我把屏蔽的//    implementation 'org.tensorflow:tensorflow-lite:2.8.0' 放出来能找到类但是运行时又报错算子丢失

**Comment by benjaminwan** [comment]
app/lib应该为app/libs

**Comment by woodboard** [comment]
抱歉犯了这种低级错误，经调试已经没有问题了，还有一个小问题再载入超长文本时貌似模型卡住了 大概超过 500字的样子这个问题能解决吗？

**Comment by benjaminwan** [comment]
长文本应该需要分段。应用端也可以做，这只是个小demo，没有实现这个功能。
