### ISSUE TITLE
如何使so文件减小？

### ISSUE THREAD

**Issue by watersoft123** [benjaminwan/ChineseTtsTflite#3]
编译后无论平台是X86或arm，tensorflow lite都会生成两个so库，而且其中一个大小都挺大，请问有没有什么方法或设置能够把这个大小给降下来？

**Comment by benjaminwan** [comment]
库是google提供的，我没有了解过能不能定制裁剪。
简单的做法是，针对不同平台去除没用用的so库，在build.gradle中配置，比如手机就保留arm的so，模拟器就保留x86的so。

**Comment by benjaminwan** [comment]
[裁剪后aar下载](https://github.com/benjaminwan/ChineseTtsTflite/releases/tag/init)

**Comment by watersoft123** [comment]
> [裁剪后aar下载](https://github.com/benjaminwan/ChineseTtsTflite/releases/tag/init)

这实在是太好了，体积大大缩小，太感谢你了！
