### ISSUE TITLE
是否可以增加isSpeaking判定？

### ISSUE THREAD

**Issue by watersoft123** [benjaminwan/ChineseTtsTflite#5]
在安卓原生TTS里面有一个isSpeaking的布尔值，可以判断播放是否正在进行。正在进行为true，播放结束为false。

**Comment by benjaminwan** [comment]
isSpeaking是在哪个类里的？有没有参考的代码？

**Comment by watersoft123** [comment]
> isSpeaking是在哪个类里的？有没有参考的代码？

应该是在android.speech.tts.TextToSpeech里面，可以参考
[这里](https://www.tabnine.com/code/java/methods/android.speech.tts.TextToSpeech/isSpeaking)

**Comment by watersoft123** [comment]
另外，关于如何缩减so二进制文件的大小，我在TensorFlow官网上找到了这样的[方法](https://tensorflow.google.cn/lite/guide/reduce_binary_size?hl=zh-cn)，我不懂C++,所以也没有尝试

**Comment by benjaminwan** [comment]
我试了一下，TextToSpeech.isSpeaking()这个方法是支持的，结果也是对的。
另外也可以通过UtteranceProgressListener获取状态。
