### ISSUE TITLE
有时会出现小的咔嚓声

### ISSUE THREAD

**Issue by Leroy-X** [benjaminwan/ChineseTtsTflite#7]
有时会出现小的轻微咔嚓声, 好像不支持中英文混读。

非常感谢开发，终于有离线的tts了
期待未来加入男声，添加更多语音模型

谢谢

**Comment by benjaminwan** [comment]
声音是靠AI模型实时生成的；
AI模型靠大量的音频通过TensorFlow框架训练出来的；
模型不是我训练，取自google的开源项目，这个项目只是作为调用demo，不是一个完善的软件；

不支持中英文，因为这个范例的模型只支持中文，如果引入单独的英文模型，对于中英文混合的句子，音频衔接不太好处理；
原始的模型是用女声训练的，而且女声的音频也是来源于公开的数据集；没有男声数据集，就算有了男声的数据集，也需要通过训练来得到对应的模型；

**Comment by Leroy-X** [comment]
非常感谢！
